PyCQA/flake8-import-order

flake8_import_order/__init__.py
using the following import:
```python
from .models import (
A,
C,
b,
)
```
I would get this message:
```
I101 Imported names are in the wrong order. Should be A, C, b
```
This happened because the comparison that the plugin does is
correct (lexicographic, case-insensitive). But when the error message is
displayed, only a lexicographic case-sensitive sorting algorithm is
used (python's default sorted)
=> fix Imported names order warning with google style

README.rst, flake8_import_order/__init__.py, tests/test_cases/complete_smarkets.py, tests/test_flake8_linter.py, tests/test_pylama_linter.py
This is equivalent to the google style except that any `import X` statements must come before any `from X import y` statments. It is roughly the same as the google style of this project before version 0.6 onwards.
I'm open to call this style anything, I've chosen smarkets as this is the style we use at Smarkets.
This should fix issue #42 .
=> Add a new smarkets style

tox.ini
The Python 3.2 tests fail due to the third party progress library no
longer supporting Python 3 below 3.3, specifically PEP-414. Dropping
the Python 3.2 tests is an easy fix justified as the last release of
Python 3.2 is 3.2.7 which was released today, see PEP-392[1].
[1]: https://www.python.org/dev/peps/pep-0392/#lifespan
=> Drop Python 3.2 test support

flake8_import_order/stdlib_list.py
The typing module has been added in to the standard library in Python
3.5.
=> Add the typing module to the stdlib list

README.rst, flake8_import_order/__init__.py, flake8_import_order/flake8_linter.py, tests/test_cases/complete_pep8.py, tests/test_flake8_linter.py, tests/test_pylama_linter.py
PEP-8 doesn't enforce sorting the imports alphanumerically inside the individual groups, however `flake8-import-order` currently does. So this PR adds an option to ignore the names for the ordering.
FWIW, I think that option should be enabled by default (it's not yet), as there IMO is no reason to be stricter than PEP-8 by default. But I leave that decision up to you guys.
=> Added 'pep8' stlye without enforcing order within the groups

README.rst
This should help users troubleshoot why an import has been classified
into a specific route.
Closes #70.
=> Clarify import classification in README

flake8_import_order/__init__.py, setup.py, tests/test_flake8_linter.py, tox.ini
The pep8 module was renamed to pycodestyle. flake8 already switched to pycodestyle 2.0.0. Because of that using flake8 and flake8-import-order results in a dependency glitch. Also the dependency pylama of flake8-import-order still uses the old package.
=> Replaced legacy pep8 with pycodestyle

flake8_import_order/flake8_linter.py
Flake8 3.0.0b1 was released 25 June 2016 and introduces some tiny
breaking changes for plugins. This adds compatibility for both Flake8
2.x and 3.x
=> Add compatibility with Flake8 3.0

flake8_import_order/stdlib_list.py, tests/test_stdlib.py
This PR adds a test that ensures stdlib imports are recognized as such.
It also fixes `concurrent` not being recognized as a stdlib import.
=> Ensure stdlib imports are recognized

flake8_import_order/checker.py, flake8_import_order/flake8_linter.py
Flake8 3.0 allows us to ask for the lines in a file instead of reading
them independently. Let's use that but default it to None for Flake8 2
compatibility.
Closes #81
=> Ask for the lines on Flake8 3.0

setup.py
Flake8 has a trove classifier on PyPI. This should new users
find flake8-import-order on PyPI when they search for Flake8
plugins.
=> Add Flake8 trove classifier

CHANGELOG.rst, README.rst, flake8_import_order/__init__.py, flake8_import_order/checker.py, flake8_import_order/flake8_linter.py, flake8_import_order/styles.py, tests/test_cases/complete_appnexus.py, tests/test_cases/complete_bad_order_appnexus.py, tests/test_flake8_linter.py, tests/test_pylama_linter.py
This is equivalent to the google style except that values specified in
the `application-package-names` option must be imported after
third-party import statements.
=> Add a new appnexus style

flake8_import_order/styles.py, tests/test_cases/wrong_from_import_same.py
Sometimes the I100 message has the unhelpful form "*from X* should be before *from X*"
Simple test case based on a real example:
```
$ more tests/test_cases/wrong_from_import_same.py
from os import system
from os import path # I100
```
Before the fix would get this:
```
$ flake8 --select I100 tests/test_cases/wrong_from_import_same.py
tests/test_cases/wrong_from_import_same.py:3:1: I100 Import statements are in the wrong order. from os should be before from os
```
With this change you get this:
```
$ flake8 --select I100 tests/test_cases/wrong_from_import_same.py
tests/test_cases/wrong_from_import_same.py:3:1: I100 Import statements are in the wrong order. path should be before system
```
=> Fix ambiguous I100 message

CHANGELOG.rst, README.rst, flake8_import_order/checker.py, flake8_import_order/styles.py, tests/test_cases/complete_edited.py, tests/test_cases/missing_newline.py, tests/test_cases/mixed_groups.py, tests/test_cases/noqa.py, tests/test_cases/wrong_from_import_order.py, tests/test_cases/wrong_import_order.py, tests/test_cases/wrong_relative_order.py, tests/test_cases/wrong_section.py, tests/test_cases/wrong_section_appnexus.py, tests/test_style_cases.py
Added ``edited`` style
``edited`` style follows the ``smarkets`` style but requires company packages
to be imported in a serparate section. Style accepts ``application_package_names``
to specify list of company packages
=> Add edited style

README.rst, flake8_import_order/checker.py, flake8_import_order/flake8_linter.py, flake8_import_order/pylama_linter.py, flake8_import_order/styles.py, setup.py, tests/test_flake8_linter.py, tests/test_style_cases.py, tox.ini
This patch replace hardcoded style names with setuptools' [entry points][1].
> Entry points are a simple way for distributions to “advertise” Python objects (such as functions or classes) for use by other distributions. Extensible applications and frameworks can search for entry points with a particular name or group, either from a specific distribution or from all active distributions on sys.path, and then inspect or load the advertised objects at will.
The group name of extensible entry points is `flake8_import_order.styles` (which follows the convention). Built-in styles also become discovered using entry points so that style names don't have to be hardcoded.
Also wrote some docs about extending styles into README.rst, but I'm unsure that my English is fine. If anyone reviews my code …
=> Make styles able to be extended by users

flake8_import_order/stdlib_list.py
The `secrets` module, which has been added in Python3.6, should be in `stdlib_list.py`
- https://www.python.org/dev/peps/pep-0506/
- https://docs.python.org/3/library/secrets.html
=> Add secrets to stdlib list

flake8_import_order/checker.py
`.group(name)` is more straightforward than `.groupdict()[name]`.
=> Simplify re group access

flake8_import_order/checker.py
We can directly use a set comprehension here instead of building and
returning an intermediate list.
=> Return parsed codes as a set()

flake8_import_order/styles.py
The previous logic would build the grouping explanation string for every
import, even if there isn't an error condition. This was unnecessary, so
we now defer that formatting work to a static method that is only
invoked when an error is detected.
Also, change the second `if` to an `elif` because these cases can't both
be true at the same time.
=> Lazily build grouping explanation string

README.rst, flake8_import_order/styles.py, tests/test_cases/additional_newline_edited.py, tests/test_cases/complete_edited.py
This is specifically helpful to allow the edited style to have an
optional newline between ``import`` and ``form X import`` lines
without triggering a I202 error.
In a more general sense this should allow for more advanced styles.
=> Allow styles an ability to override the actual checks

README.rst, flake8_import_order/styles.py, setup.py
PyCharm's import settings is closest to Smarkets, but it's sorting is case sensitive. So this PR implements a new style for PyCharm only.
But I'm not sure if it's appropriate to put a specific IDE import style here.
Please leave comment if any question.
=> feat: implement PyCharm import style

flake8_import_order/styles.py, tests/test_cases/complete_pycharm.py
Pycharm sorts imports over multiple line case-sensitive.
The following should be a valid import order.
import B
import a
Also added a pycharm test case.
Closes-issue: #158
=> Fix case-sensitive related I100 errors for the pycharm style.

flake8_import_order/checker.py
Regular expression for finding `# noqa` comments produces `DeprecationWarning: invalid escape sequence \s` when installing flake8-import-order as a requirement in setup.py. This line also fails `pycodestyle` check with message `W605 - invalid escape sequence '\s'`.
Environment to reproduce - python3.7, setuptools 39.0.1.
=> Fix warning in noqa regexp

flake8_import_order/stdlib_list.py
The module was introduced in 3.3.
See: https://bugs.python.org/issue11750
=> Recognize _winapi as stdlib

flake8_import_order/flake8_linter.py
flake8 uses only argparse option styles now, use
str instead of "string" for types given.
Fixes: #189
=> repair register opt calls

flake8_import_order/stdlib_list.py, tests/test_stdlib.py
Please tag a new release with this change
=> Recognize zoneinfo introduced in python 3.9 as stdlib

.github/workflows/tox.yml
Test results: https://github.com/cclauss/flake8-import-order/actions
https://travis-ci.org/github/PyCQA/flake8-import-order/builds
=> GitHub Action to run tox to replace Travis CI

CHANGELOG.rst
https://pypi.org/project/codespell Fixes the existence of specifying statements.
=> Fix typos discovered by codespell

setup.cfg
=> Add python_requires to setup.cfg
